
package charmap

func init() {

	charmapDecode := map[byte]rune{
		'\x00':	'\u0000',	 // NULL
		'\x01':	'\u0001',	 // START OF HEADING
		'\x02':	'\u0002',	 // START OF TEXT
		'\x03':	'\u0003',	 // END OF TEXT
		'\x04':	'\u0004',	 // END OF TRANSMISSION
		'\x05':	'\u0005',	 // ENQUIRY
		'\x06':	'\u0006',	 // ACKNOWLEDGE
		'\x07':	'\u0007',	 // BELL
		'\x08':	'\u0008',	 // BACKSPACE
		'\x09':	'\u0009',	 // HORIZONTAL TABULATION
		'\x0A':	'\u000A',	 // LINE FEED
		'\x0B':	'\u000B',	 // VERTICAL TABULATION
		'\x0C':	'\u000C',	 // FORM FEED
		'\x0D':	'\u000D',	 // CARRIAGE RETURN
		'\x0E':	'\u000E',	 // SHIFT OUT
		'\x0F':	'\u000F',	 // SHIFT IN
		'\x10':	'\u0010',	 // DATA LINK ESCAPE
		'\x11':	'\u0011',	 // DEVICE CONTROL ONE
		'\x12':	'\u0012',	 // DEVICE CONTROL TWO
		'\x13':	'\u0013',	 // DEVICE CONTROL THREE
		'\x14':	'\u0014',	 // DEVICE CONTROL FOUR
		'\x15':	'\u0015',	 // NEGATIVE ACKNOWLEDGE
		'\x16':	'\u0016',	 // SYNCHRONOUS IDLE
		'\x17':	'\u0017',	 // END OF TRANSMISSION BLOCK
		'\x18':	'\u0018',	 // CANCEL
		'\x19':	'\u0019',	 // END OF MEDIUM
		'\x1A':	'\u001A',	 // SUBSTITUTE
		'\x1B':	'\u001B',	 // ESCAPE
		'\x1C':	'\u001C',	 // FILE SEPARATOR
		'\x1D':	'\u001D',	 // GROUP SEPARATOR
		'\x1E':	'\u001E',	 // RECORD SEPARATOR
		'\x1F':	'\u001F',	 // UNIT SEPARATOR
		'\x20':	'\u0020',	 // SPACE
		'\x21':	'\u0021',	 // EXCLAMATION MARK
		'\x22':	'\u0022',	 // QUOTATION MARK
		'\x23':	'\u0023',	 // NUMBER SIGN
		'\x24':	'\u0024',	 // DOLLAR SIGN
		'\x25':	'\u0025',	 // PERCENT SIGN
		'\x26':	'\u0026',	 // AMPERSAND
		'\x27':	'\u0027',	 // APOSTROPHE
		'\x28':	'\u0028',	 // LEFT PARENTHESIS
		'\x29':	'\u0029',	 // RIGHT PARENTHESIS
		'\x2A':	'\u002A',	 // ASTERISK
		'\x2B':	'\u002B',	 // PLUS SIGN
		'\x2C':	'\u002C',	 // COMMA
		'\x2D':	'\u002D',	 // HYPHEN-MINUS
		'\x2E':	'\u002E',	 // FULL STOP
		'\x2F':	'\u002F',	 // SOLIDUS
		'\x30':	'\u0030',	 // DIGIT ZERO
		'\x31':	'\u0031',	 // DIGIT ONE
		'\x32':	'\u0032',	 // DIGIT TWO
		'\x33':	'\u0033',	 // DIGIT THREE
		'\x34':	'\u0034',	 // DIGIT FOUR
		'\x35':	'\u0035',	 // DIGIT FIVE
		'\x36':	'\u0036',	 // DIGIT SIX
		'\x37':	'\u0037',	 // DIGIT SEVEN
		'\x38':	'\u0038',	 // DIGIT EIGHT
		'\x39':	'\u0039',	 // DIGIT NINE
		'\x3A':	'\u003A',	 // COLON
		'\x3B':	'\u003B',	 // SEMICOLON
		'\x3C':	'\u003C',	 // LESS-THAN SIGN
		'\x3D':	'\u003D',	 // EQUALS SIGN
		'\x3E':	'\u003E',	 // GREATER-THAN SIGN
		'\x3F':	'\u003F',	 // QUESTION MARK
		'\x40':	'\u0040',	 // COMMERCIAL AT
		'\x41':	'\u0041',	 // LATIN CAPITAL LETTER A
		'\x42':	'\u0042',	 // LATIN CAPITAL LETTER B
		'\x43':	'\u0043',	 // LATIN CAPITAL LETTER C
		'\x44':	'\u0044',	 // LATIN CAPITAL LETTER D
		'\x45':	'\u0045',	 // LATIN CAPITAL LETTER E
		'\x46':	'\u0046',	 // LATIN CAPITAL LETTER F
		'\x47':	'\u0047',	 // LATIN CAPITAL LETTER G
		'\x48':	'\u0048',	 // LATIN CAPITAL LETTER H
		'\x49':	'\u0049',	 // LATIN CAPITAL LETTER I
		'\x4A':	'\u004A',	 // LATIN CAPITAL LETTER J
		'\x4B':	'\u004B',	 // LATIN CAPITAL LETTER K
		'\x4C':	'\u004C',	 // LATIN CAPITAL LETTER L
		'\x4D':	'\u004D',	 // LATIN CAPITAL LETTER M
		'\x4E':	'\u004E',	 // LATIN CAPITAL LETTER N
		'\x4F':	'\u004F',	 // LATIN CAPITAL LETTER O
		'\x50':	'\u0050',	 // LATIN CAPITAL LETTER P
		'\x51':	'\u0051',	 // LATIN CAPITAL LETTER Q
		'\x52':	'\u0052',	 // LATIN CAPITAL LETTER R
		'\x53':	'\u0053',	 // LATIN CAPITAL LETTER S
		'\x54':	'\u0054',	 // LATIN CAPITAL LETTER T
		'\x55':	'\u0055',	 // LATIN CAPITAL LETTER U
		'\x56':	'\u0056',	 // LATIN CAPITAL LETTER V
		'\x57':	'\u0057',	 // LATIN CAPITAL LETTER W
		'\x58':	'\u0058',	 // LATIN CAPITAL LETTER X
		'\x59':	'\u0059',	 // LATIN CAPITAL LETTER Y
		'\x5A':	'\u005A',	 // LATIN CAPITAL LETTER Z
		'\x5B':	'\u005B',	 // LEFT SQUARE BRACKET
		'\x5C':	'\u005C',	 // REVERSE SOLIDUS
		'\x5D':	'\u005D',	 // RIGHT SQUARE BRACKET
		'\x5E':	'\u005E',	 // CIRCUMFLEX ACCENT
		'\x5F':	'\u005F',	 // LOW LINE
		'\x60':	'\u0060',	 // GRAVE ACCENT
		'\x61':	'\u0061',	 // LATIN SMALL LETTER A
		'\x62':	'\u0062',	 // LATIN SMALL LETTER B
		'\x63':	'\u0063',	 // LATIN SMALL LETTER C
		'\x64':	'\u0064',	 // LATIN SMALL LETTER D
		'\x65':	'\u0065',	 // LATIN SMALL LETTER E
		'\x66':	'\u0066',	 // LATIN SMALL LETTER F
		'\x67':	'\u0067',	 // LATIN SMALL LETTER G
		'\x68':	'\u0068',	 // LATIN SMALL LETTER H
		'\x69':	'\u0069',	 // LATIN SMALL LETTER I
		'\x6A':	'\u006A',	 // LATIN SMALL LETTER J
		'\x6B':	'\u006B',	 // LATIN SMALL LETTER K
		'\x6C':	'\u006C',	 // LATIN SMALL LETTER L
		'\x6D':	'\u006D',	 // LATIN SMALL LETTER M
		'\x6E':	'\u006E',	 // LATIN SMALL LETTER N
		'\x6F':	'\u006F',	 // LATIN SMALL LETTER O
		'\x70':	'\u0070',	 // LATIN SMALL LETTER P
		'\x71':	'\u0071',	 // LATIN SMALL LETTER Q
		'\x72':	'\u0072',	 // LATIN SMALL LETTER R
		'\x73':	'\u0073',	 // LATIN SMALL LETTER S
		'\x74':	'\u0074',	 // LATIN SMALL LETTER T
		'\x75':	'\u0075',	 // LATIN SMALL LETTER U
		'\x76':	'\u0076',	 // LATIN SMALL LETTER V
		'\x77':	'\u0077',	 // LATIN SMALL LETTER W
		'\x78':	'\u0078',	 // LATIN SMALL LETTER X
		'\x79':	'\u0079',	 // LATIN SMALL LETTER Y
		'\x7A':	'\u007A',	 // LATIN SMALL LETTER Z
		'\x7B':	'\u007B',	 // LEFT CURLY BRACKET
		'\x7C':	'\u007C',	 // VERTICAL LINE
		'\x7D':	'\u007D',	 // RIGHT CURLY BRACKET
		'\x7E':	'\u007E',	 // TILDE
		'\x7F':	'\u007F',	 // DELETE
		'\x80':	'\u00C4',	 // LATIN CAPITAL LETTER A WITH DIAERESIS
		'\x81':	'\u0100',	 // LATIN CAPITAL LETTER A WITH MACRON
		'\x82':	'\u0101',	 // LATIN SMALL LETTER A WITH MACRON
		'\x83':	'\u00C9',	 // LATIN CAPITAL LETTER E WITH ACUTE
		'\x84':	'\u0104',	 // LATIN CAPITAL LETTER A WITH OGONEK
		'\x85':	'\u00D6',	 // LATIN CAPITAL LETTER O WITH DIAERESIS
		'\x86':	'\u00DC',	 // LATIN CAPITAL LETTER U WITH DIAERESIS
		'\x87':	'\u00E1',	 // LATIN SMALL LETTER A WITH ACUTE
		'\x88':	'\u0105',	 // LATIN SMALL LETTER A WITH OGONEK
		'\x89':	'\u010C',	 // LATIN CAPITAL LETTER C WITH CARON
		'\x8A':	'\u00E4',	 // LATIN SMALL LETTER A WITH DIAERESIS
		'\x8B':	'\u010D',	 // LATIN SMALL LETTER C WITH CARON
		'\x8C':	'\u0106',	 // LATIN CAPITAL LETTER C WITH ACUTE
		'\x8D':	'\u0107',	 // LATIN SMALL LETTER C WITH ACUTE
		'\x8E':	'\u00E9',	 // LATIN SMALL LETTER E WITH ACUTE
		'\x8F':	'\u0179',	 // LATIN CAPITAL LETTER Z WITH ACUTE
		'\x90':	'\u017A',	 // LATIN SMALL LETTER Z WITH ACUTE
		'\x91':	'\u010E',	 // LATIN CAPITAL LETTER D WITH CARON
		'\x92':	'\u00ED',	 // LATIN SMALL LETTER I WITH ACUTE
		'\x93':	'\u010F',	 // LATIN SMALL LETTER D WITH CARON
		'\x94':	'\u0112',	 // LATIN CAPITAL LETTER E WITH MACRON
		'\x95':	'\u0113',	 // LATIN SMALL LETTER E WITH MACRON
		'\x96':	'\u0116',	 // LATIN CAPITAL LETTER E WITH DOT ABOVE
		'\x97':	'\u00F3',	 // LATIN SMALL LETTER O WITH ACUTE
		'\x98':	'\u0117',	 // LATIN SMALL LETTER E WITH DOT ABOVE
		'\x99':	'\u00F4',	 // LATIN SMALL LETTER O WITH CIRCUMFLEX
		'\x9A':	'\u00F6',	 // LATIN SMALL LETTER O WITH DIAERESIS
		'\x9B':	'\u00F5',	 // LATIN SMALL LETTER O WITH TILDE
		'\x9C':	'\u00FA',	 // LATIN SMALL LETTER U WITH ACUTE
		'\x9D':	'\u011A',	 // LATIN CAPITAL LETTER E WITH CARON
		'\x9E':	'\u011B',	 // LATIN SMALL LETTER E WITH CARON
		'\x9F':	'\u00FC',	 // LATIN SMALL LETTER U WITH DIAERESIS
		'\xA0':	'\u2020',	 // DAGGER
		'\xA1':	'\u00B0',	 // DEGREE SIGN
		'\xA2':	'\u0118',	 // LATIN CAPITAL LETTER E WITH OGONEK
		'\xA3':	'\u00A3',	 // POUND SIGN
		'\xA4':	'\u00A7',	 // SECTION SIGN
		'\xA5':	'\u2022',	 // BULLET
		'\xA6':	'\u00B6',	 // PILCROW SIGN
		'\xA7':	'\u00DF',	 // LATIN SMALL LETTER SHARP S
		'\xA8':	'\u00AE',	 // REGISTERED SIGN
		'\xA9':	'\u00A9',	 // COPYRIGHT SIGN
		'\xAA':	'\u2122',	 // TRADE MARK SIGN
		'\xAB':	'\u0119',	 // LATIN SMALL LETTER E WITH OGONEK
		'\xAC':	'\u00A8',	 // DIAERESIS
		'\xAD':	'\u2260',	 // NOT EQUAL TO
		'\xAE':	'\u0123',	 // LATIN SMALL LETTER G WITH CEDILLA
		'\xAF':	'\u012E',	 // LATIN CAPITAL LETTER I WITH OGONEK
		'\xB0':	'\u012F',	 // LATIN SMALL LETTER I WITH OGONEK
		'\xB1':	'\u012A',	 // LATIN CAPITAL LETTER I WITH MACRON
		'\xB2':	'\u2264',	 // LESS-THAN OR EQUAL TO
		'\xB3':	'\u2265',	 // GREATER-THAN OR EQUAL TO
		'\xB4':	'\u012B',	 // LATIN SMALL LETTER I WITH MACRON
		'\xB5':	'\u0136',	 // LATIN CAPITAL LETTER K WITH CEDILLA
		'\xB6':	'\u2202',	 // PARTIAL DIFFERENTIAL
		'\xB7':	'\u2211',	 // N-ARY SUMMATION
		'\xB8':	'\u0142',	 // LATIN SMALL LETTER L WITH STROKE
		'\xB9':	'\u013B',	 // LATIN CAPITAL LETTER L WITH CEDILLA
		'\xBA':	'\u013C',	 // LATIN SMALL LETTER L WITH CEDILLA
		'\xBB':	'\u013D',	 // LATIN CAPITAL LETTER L WITH CARON
		'\xBC':	'\u013E',	 // LATIN SMALL LETTER L WITH CARON
		'\xBD':	'\u0139',	 // LATIN CAPITAL LETTER L WITH ACUTE
		'\xBE':	'\u013A',	 // LATIN SMALL LETTER L WITH ACUTE
		'\xBF':	'\u0145',	 // LATIN CAPITAL LETTER N WITH CEDILLA
		'\xC0':	'\u0146',	 // LATIN SMALL LETTER N WITH CEDILLA
		'\xC1':	'\u0143',	 // LATIN CAPITAL LETTER N WITH ACUTE
		'\xC2':	'\u00AC',	 // NOT SIGN
		'\xC3':	'\u221A',	 // SQUARE ROOT
		'\xC4':	'\u0144',	 // LATIN SMALL LETTER N WITH ACUTE
		'\xC5':	'\u0147',	 // LATIN CAPITAL LETTER N WITH CARON
		'\xC6':	'\u2206',	 // INCREMENT
		'\xC7':	'\u00AB',	 // LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
		'\xC8':	'\u00BB',	 // RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
		'\xC9':	'\u2026',	 // HORIZONTAL ELLIPSIS
		'\xCA':	'\u00A0',	 // NO-BREAK SPACE
		'\xCB':	'\u0148',	 // LATIN SMALL LETTER N WITH CARON
		'\xCC':	'\u0150',	 // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
		'\xCD':	'\u00D5',	 // LATIN CAPITAL LETTER O WITH TILDE
		'\xCE':	'\u0151',	 // LATIN SMALL LETTER O WITH DOUBLE ACUTE
		'\xCF':	'\u014C',	 // LATIN CAPITAL LETTER O WITH MACRON
		'\xD0':	'\u2013',	 // EN DASH
		'\xD1':	'\u2014',	 // EM DASH
		'\xD2':	'\u201C',	 // LEFT DOUBLE QUOTATION MARK
		'\xD3':	'\u201D',	 // RIGHT DOUBLE QUOTATION MARK
		'\xD4':	'\u2018',	 // LEFT SINGLE QUOTATION MARK
		'\xD5':	'\u2019',	 // RIGHT SINGLE QUOTATION MARK
		'\xD6':	'\u00F7',	 // DIVISION SIGN
		'\xD7':	'\u25CA',	 // LOZENGE
		'\xD8':	'\u014D',	 // LATIN SMALL LETTER O WITH MACRON
		'\xD9':	'\u0154',	 // LATIN CAPITAL LETTER R WITH ACUTE
		'\xDA':	'\u0155',	 // LATIN SMALL LETTER R WITH ACUTE
		'\xDB':	'\u0158',	 // LATIN CAPITAL LETTER R WITH CARON
		'\xDC':	'\u2039',	 // SINGLE LEFT-POINTING ANGLE QUOTATION MARK
		'\xDD':	'\u203A',	 // SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
		'\xDE':	'\u0159',	 // LATIN SMALL LETTER R WITH CARON
		'\xDF':	'\u0156',	 // LATIN CAPITAL LETTER R WITH CEDILLA
		'\xE0':	'\u0157',	 // LATIN SMALL LETTER R WITH CEDILLA
		'\xE1':	'\u0160',	 // LATIN CAPITAL LETTER S WITH CARON
		'\xE2':	'\u201A',	 // SINGLE LOW-9 QUOTATION MARK
		'\xE3':	'\u201E',	 // DOUBLE LOW-9 QUOTATION MARK
		'\xE4':	'\u0161',	 // LATIN SMALL LETTER S WITH CARON
		'\xE5':	'\u015A',	 // LATIN CAPITAL LETTER S WITH ACUTE
		'\xE6':	'\u015B',	 // LATIN SMALL LETTER S WITH ACUTE
		'\xE7':	'\u00C1',	 // LATIN CAPITAL LETTER A WITH ACUTE
		'\xE8':	'\u0164',	 // LATIN CAPITAL LETTER T WITH CARON
		'\xE9':	'\u0165',	 // LATIN SMALL LETTER T WITH CARON
		'\xEA':	'\u00CD',	 // LATIN CAPITAL LETTER I WITH ACUTE
		'\xEB':	'\u017D',	 // LATIN CAPITAL LETTER Z WITH CARON
		'\xEC':	'\u017E',	 // LATIN SMALL LETTER Z WITH CARON
		'\xED':	'\u016A',	 // LATIN CAPITAL LETTER U WITH MACRON
		'\xEE':	'\u00D3',	 // LATIN CAPITAL LETTER O WITH ACUTE
		'\xEF':	'\u00D4',	 // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
		'\xF0':	'\u016B',	 // LATIN SMALL LETTER U WITH MACRON
		'\xF1':	'\u016E',	 // LATIN CAPITAL LETTER U WITH RING ABOVE
		'\xF2':	'\u00DA',	 // LATIN CAPITAL LETTER U WITH ACUTE
		'\xF3':	'\u016F',	 // LATIN SMALL LETTER U WITH RING ABOVE
		'\xF4':	'\u0170',	 // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
		'\xF5':	'\u0171',	 // LATIN SMALL LETTER U WITH DOUBLE ACUTE
		'\xF6':	'\u0172',	 // LATIN CAPITAL LETTER U WITH OGONEK
		'\xF7':	'\u0173',	 // LATIN SMALL LETTER U WITH OGONEK
		'\xF8':	'\u00DD',	 // LATIN CAPITAL LETTER Y WITH ACUTE
		'\xF9':	'\u00FD',	 // LATIN SMALL LETTER Y WITH ACUTE
		'\xFA':	'\u0137',	 // LATIN SMALL LETTER K WITH CEDILLA
		'\xFB':	'\u017B',	 // LATIN CAPITAL LETTER Z WITH DOT ABOVE
		'\xFC':	'\u0141',	 // LATIN CAPITAL LETTER L WITH STROKE
		'\xFD':	'\u017C',	 // LATIN SMALL LETTER Z WITH DOT ABOVE
		'\xFE':	'\u0122',	 // LATIN CAPITAL LETTER G WITH CEDILLA
		'\xFF':	'\u02C7',	 // CARON

	}

	charmapEncode := reverseByteRuneMap(charmapDecode)

	newCodec := &codecMap8Bit{EncodeMap: charmapEncode, DecodeMap: charmapDecode}

	register(newCodec, "MAC-LATIN2", "MACLATIN2")

}
